### ISSUE TITLE
🐞 BugFix `mgm-hurry download_static_pairlist`

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/MoniGoMani#135]
Forgot to test the updates to the new `download_static_pairlist` command, I'll be ironing these out as first because they also break the `up` command.
```powershell
INFO - 💨 💨 💨
       👉 Download Top Volume Static Pairlist
       💨 💨 💨
INFO - 🤖 Generating new static pairlist...
? How much pairs would you like in your TopVolumeStaticPairList? (1 - 200) 15
WARNING - 🤷 No "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/temp/freqtrade-mgm/user_data/mgm-config-hyperopt.json" file found in the "user_data" directory. Please run: mgm-hurry setup
INFO - 👉 Added 9 extra days to the timerange for the "startup_candle_count"
Traceback (most recent call last):
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/temp/freqtrade-mgm/./monigomani/mgm-hurry", line 979, in <module>
    fire.Fire(MGMHurry)
  File "/home/rikj000/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/rikj000/.local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/rikj000/.local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/temp/freqtrade-mgm/./monigomani/mgm-hurry", line 127, in up
    self.download_static_pairlist()
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/temp/freqtrade-mgm/./monigomani/mgm-hurry", line 584, in download_static_pairlist
    static_pairlist = self.freqtrade_cli.download_static_pairlist(
  File "/mnt/Windows/Users/Rik/Desktop/Rikj-Home/Projects/temp/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 282, in download_static_pairlist
    retrieve_json_object['pairlist'][1]['min_days_listed'] = min_days_listed
KeyError: 'pairlist'
```

**Comment by Rikj000** [comment]
Fixed with commit: https://github.com/Rikj000/MoniGoMani/commit/a6375f0fcd52a8fcbbb97b6b4a24cc2492590b47
