### ISSUE TITLE
🐞 mgm on docker

### ISSUE THREAD

**Issue by ghost** [Rikj000/MoniGoMani#153]
Hello, im downgrade freqtrade version but nothing has changed.  My image is hoanghnbk/freqtrade_3503fdb4, but i get the same error

docker-compose run freqtrade trade --strategy MasterMoniGoManiHyperStrategy -c user_data/mgm-config.example.json

2021-10-07 13:21:38,695 - freqtrade.worker - INFO - Starting worker develop
2021-10-07 13:21:38,695 - freqtrade.configuration.configuration - INFO - Using config: user_data/mgm-config.example.json ...
2021-10-07 13:21:38,703 - freqtrade.loggers - INFO - Verbosity set to 0
2021-10-07 13:21:38,704 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-10-07 13:21:38,704 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-10-07 13:21:38,704 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2021-10-07 13:21:38,704 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2021-10-07 13:21:38,844 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-10-07 13:21:38,845 - freqtrade.commands.trade_commands - ERROR - 'NoneType' object has no attribute 'lower'
2021-10-07 13:21:38,845 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 105, in load_config
    self._process_optimize_options(config)
  File "/freqtrade/freqtrade/configuration/configuration.py", line 252, in _process_optimize_options
    self._process_datadir_options(config)
  File "/freqtrade/freqtrade/configuration/configuration.py", line 193, in _process_datadir_options
    config.update({'datadir': create_datadir(config, self.args.get('datadir', None))})
  File "/freqtrade/freqtrade/configuration/directory_operations.py", line 18, in create_datadir
    exchange_name = config.get('exchange', {}).get('name').lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Rikj000** [comment]
I will be sure to remove docker support tonight

**Comment by ghost** [comment]
okay BOSSS UP TO YOU
