### ISSUE TITLE
🐞 macOS Big Sur `mgm-hurry install_freqtrade` error

### ISSUE THREAD

**Issue by mubeguku** [Rikj000/MoniGoMani#154]
Hello.

I'm getting an error on "python3 mgm-hurry hyperopt". Any ideas? Xcode command-line tools are installed.

```
WARNING - FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/bin/freqtrade.
WARNING - 🤷 No Freqtrade installation found. Please run "mgm-hurry install_freqtrade" before attempting to go further!
INFO - 💨 💨 💨
       👉 Starting HyperOpt run. Keep calm while your computer burns 🔥
       💨 💨 💨
Traceback (most recent call last):
  File "/Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/mgm-hurry", line 1079, in <module>
    fire.Fire(MGMHurry)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/mgm-hurry", line 712, in hyperopt
    self.monigomani_cli.run_command(command=command, output_file_name=output_file_path,hyperopt=True)
  File "/Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/MoniGoManiCli.py", line 264, in run_command
    output_file = open(output_file_name, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/user_data/hyperopt_results/HyperOptResults-MoniGoManiHyperStrategy-2021-10-07_19-58-48.log' 
```

**Comment by Rikj000** [comment]
> ```
> WARNING - FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/bin/freqtrade.
> WARNING - 🤷 No Freqtrade installation found. Please run "mgm-hurry install_freqtrade" before attempting to go further!
> ```

Your issue is not directly due to `mgm-hurry hyperopt`.
It's the effect of some error that occured during `mgm-hurry install_freqtrade`.
Re-try that command and take note of any errors that might occur,
please keep us posted how it went!

**Comment by mubeguku** [comment]
Thanks! I'm getting two errors after running install_freqtrade:

```
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for tables, since package 'wheel' is not installed.
Using legacy 'setup.py install' for sdnotify, since package 'wheel' is not installed.
Using legacy 'setup.py install' for docopt, since package 'wheel' is not installed.
Building wheels for collected packages: py-find-1st
  Building wheel for py-find-1st (PEP 517) ... done
  Created wheel for py-find-1st: filename=py_find_1st-1.1.5-cp39-cp39-macosx_11_0_x86_64.whl size=7957 sha256=6ec1a0f5ffc6768f7ee90cb77952546cd05ee8b5cf26db8149ec31b846fec680
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-1ctcx0g0/wheels/bf/c1/49/5439f3dd8159a3d27336f734925c355fe86c73f231d5c4748a
Successfully built py-find-1st
Installing collected packages: traitlets, six, pyrsistent, pycparser, attrs, tornado, pyzmq, python-dateutil, pyparsing, numpy, nest-asyncio, multidict, jupyter-core, jsonschema, ipython-genutils, idna, entrypoints, cffi, yarl, webencodings, wcwidth, urllib3, tzlocal, typing-extensions, toml, threadpoolctl, scipy, PyYAML, pytz, pygments, pyflakes, pycodestyle, pycares, py, pluggy, packaging, nbformat, mccabe, MarkupSafe, jupyter-client, joblib, iniconfig, chardet, certifi, async-timeout, testpath, tenacity, TA-Lib, starlette, scikit-learn, requests, python-utils, pytest, pydantic, pyaml, prompt-toolkit, pandocfilters, pandas, numexpr, nbclient, mypy-extensions, mistune, jupyterlab-pygments, jinja2, h11, greenlet, flake8, docopt, defusedxml, cryptography, coverage, click, cachetools, bleach, asgiref, arrow, APScheduler, aiohttp, aiodns, wrapt, uvicorn, types-tabulate, types-requests, types-filelock, types-cachetools, technical, tabulate, tables, SQLAlchemy, sdnotify, scikit-optimize, questionary, python-telegram-bot, python-rapidjson, pytest-random-order, pytest-mock, pytest-cov, pytest-asyncio, pyjwt, pycoingecko, py-find-1st, psutil, progressbar2, plotly, nbconvert, mypy, isort, flake8-type-annotations, flake8-tidy-imports, filelock, fastapi, coveralls, colorama, ccxt, blosc, aiofiles
    Running setup.py install for TA-Lib ... done
    Running setup.py install for docopt ... done
    Running setup.py install for wrapt ... done
    Running setup.py install for tables ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-e5dtmr97/tables_2ffcee89e8964b1999c41fef588f706a/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-e5dtmr97/tables_2ffcee89e8964b1999c41fef588f706a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-2ji4p5ee/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/include/site/python3.9/tables
         cwd: /private/tmp/pip-install-e5dtmr97/tables_2ffcee89e8964b1999c41fef588f706a/
```

 ```
c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:256:24: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            state->start = LSEEK(state->fd, 0, SEEK_CUR);
                           ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
    #  define LSEEK lseek
                    ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:256:24: note: did you mean 'fseek'?
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
    #  define LSEEK lseek
                    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
    int      fseek(FILE *, long, int);
             ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:355:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
            ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
    #  define LSEEK lseek
                    ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:396:15: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
                  ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
    #  define LSEEK lseek
                    ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:492:14: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        offset = LSEEK(state->fd, 0, SEEK_CUR);
                 ^
    c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
    #  define LSEEK lseek
                    ^
    4 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-e5dtmr97/tables_2ffcee89e8964b1999c41fef588f706a/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-e5dtmr97/tables_2ffcee89e8964b1999c41fef588f706a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-2ji4p5ee/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mihkelsaariste/Documents/Robot/freqtrade-mgm/.env/include/site/python3.9/tables Check the logs for full command output.
Failed installing dependencies

```

**Comment by mubeguku** [comment]
I also tried to install "pip3 install wheel" but it says: "Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (0.37.0)"

**Comment by taina0407** [comment]
> I also tried to install "pip3 install wheel" but it says: "Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (0.37.0)"

Can you try "brew install hdf5" and then try to install again ?

**Comment by mubeguku** [comment]
Thank you everyone for the help! Finally I was able to make it work!

$ brew install c-blosc
$ pip3 install tables
$ sudo mgm-hurry install_freqtrade

**Comment by Rikj000** [comment]
> 
> 
> Thank you everyone for the help! Finally I was able to make it work!
> 
> $ brew install c-blosc $ pip3 install tables $ sudo mgm-hurry install_freqtrade

Did you also install hdf5?
I'll update the MacOS installation notes soon with these findings, thank you guys 🦾

**Comment by mubeguku** [comment]
I think it was installed earlier, yep:

```
hdf5: stable 1.12.1 (bottled)
File format designed to store large amounts of data
https://www.hdfgroup.org/HDF5
Conflicts with:
  hdf5-mpi (because hdf5-mpi is a variant of hdf5, one can only use one or the other)
/usr/local/Cellar/hdf5/1.12.1 (273 files, 18.3MB) *
  Poured from bottle on 2021-10-06 at 22:08:13
```

**Comment by Rikj000** [comment]
Nice, closing the issue, docs are edited accordingly now :)
