### ISSUE TITLE
❓ Installation error Python `v3.7`

### ISSUE THREAD

**Issue by NL647** [Rikj000/MoniGoMani#171]
Hello , I tried to install the project using the installer on Debian `v9` and Python `v3.7.3` and i always get an error.
All dependencies are installed correctly.
Do someone know how to fix it please?
Thank s for you help.

```log
WARNING - FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /home/sky/freqtrade-mgm/.env/bin/freqtrade.
✔ 👉  Clone Freqtrade repository and resetting to commit 3503fdb4ec31be99f433fdce039543e0911964d6
Traceback (most recent call last):
  File "./monigomani/mgm-hurry", line 1150, in <module>
    fire.Fire(MGMHurry)
  File "/home/sky/.local/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/sky/.local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/sky/.local/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./monigomani/mgm-hurry", line 140, in up
    self.install_freqtrade()
  File "./monigomani/mgm-hurry", line 252, in install_freqtrade
    commit=commit, install_ui=install_ui)
  File "/home/sky/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 190, in download_setup_freqtrade
    self.copy_installation_files(temp_dirname, target_dir)
  File "/home/sky/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 218, in copy_installation_files
    copytree(temp_dirname, target_dir, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
```

**Comment by Rikj000** [comment]
As you can read under [`VeryQuickStart - Requirements`](https://github.com/Rikj000/MoniGoMani/blob/development/Documentation/Docs-VeryQuickStart.md#requirements), MoniGoMani currently requires Python `v3.8.0` or above.
