### ISSUE TITLE
❓ Unable to install on `python 3.7`

### ISSUE THREAD

**Issue by bibinvargheset** [Rikj000/MoniGoMani#209]
Traceback (most recent call last):
  File "./monigomani/mgm-hurry", line 1164, in <module>
    fire.Fire(MGMHurry)
  File "/home/bibin/anaconda3/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bibin/anaconda3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/bibin/anaconda3/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./monigomani/mgm-hurry", line 140, in up
    self.install_freqtrade()
  File "./monigomani/mgm-hurry", line 252, in install_freqtrade
    commit=commit, install_ui=install_ui)
  File "/mnt/f/python/stocks/freqtrade/freq-mgm/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 190, in download_setup_freqtrade
    self.copy_installation_files(temp_dirname, target_dir)
  File "/mnt/f/python/stocks/freqtrade/freq-mgm/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 218, in copy_installation_files
    copytree(temp_dirname, target_dir, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'

is there a docker avaliable?

**Comment by Rikj000** [comment]
You're trying to install MGM on Python 3.7.
While in the requirements it mentions that it requires Python +3.8.
So you're running into issues due to that.

`docker` currently is **not** supported by MGM,
however I'm working on `pyenv` & `pipenv` integration.
Which will remove the Python +3.8 dependency & which will allow MGM to install on OSes with older Python versions.
See issue #206
