### ISSUE TITLE
❓ ModuleNotFoundError: No module named `_bz2`

### ISSUE THREAD

**Issue by raftersvk** [Rikj000/MoniGoMani#244]
i wanted to do a complete new and fresh install running the given install command from the doc (via installer.sh).
Unfortunately I have this error during installation :
`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ⚙️  Proceeding to Freqtrade & MoniGoMani installation...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Traceback (most recent call last):
  File "/root/Freqtrade-MGM/monigomani/mgm-hurry", line 29, in <module>
    import pandas as pd  # noqa
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/root/.local/share/virtualenvs/Freqtrade-MGM-oqDwSHaA/lib/python3.9/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/root/.pyenv/versions/3.9.9/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'`

I have tried to install missing libraries via :
`sudo apt-get install libbz2-dev`

but I get the same error after trying again to install.

Info :
- Ubuntu version : Ubuntu 20.04.3 LTS

it looks like it is missing some files in the pip environment, but what ? where ?

**Comment by Rikj000** [comment]
Seems like you're missing the `bz2` package for some reason.. 🤔
Which is odd, since `bzip2` is not on [`pypi`](https://pypi.org/),   
I believe it's a default package that usually should ship with your python by default.

I've done some research around this though, interesting links:
- https://stackoverflow.com/questions/50335503/no-module-named-bz2-in-python3
- https://github.com/freqtrade/freqtrade/issues/2245

The StackOverflow post suggests installing a virtual python 3.9 with `pyenv`,
and then perhaps also setting it as your local/system default.

However I'm not marking this as a bug yet, since it's the 1st report I hear about this on Ubuntu,   
and I'm quite sure a lot of users where able to install on Ubuntu without issues.
