### ISSUE TITLE
Installation+config issue on Download pairlist

### ISSUE THREAD

**Issue by pdiana4** [Rikj000/MoniGoMani#345]
**Hi, I was installing MGM on my other macbook when I've encountered these 2 problems:

#1 installation via script get stuck during freqtrade installing process:**

ERROR: Could not find a version that satisfies the requirement ccxt==1.61.92 (from versions: --ALL VERSION LISTED- but 1.61.92 not listed)
...
ERROR: No matching distribution found for ccxt==1.61.92
Failed installing dependencies
INFO - 👉 MGM-Hurry will now run the following command for you:
 . "/Users/pierlu/Freqtrade-MGM/.env/bin/activate"; freqtrade install-ui
/bin/sh: freqtrade: command not found
INFO - ✔ Successfully installed FreqUI!
...

**---> "workaround": I've installed freqtrade separately (cloned in mgm folder, and than copied all .env folder from freqtrade to MGM folder, no warning shows up so I assume the installation is fine but when I try to download pairlist here we go again, another issue:** 

INFO - 💨 💨 💨
       👉 Download Top Volume Static Pairlist
       💨 💨 💨
INFO - 🤖 Generating new static pairlist...
? How much pairs would you like in your TopVolumeStaticPairList? (1 - 200) 15
INFO - 👉 Added 9 extra days to the timerange for the "startup_candle_count"
INFO - 👉 MGM-Hurry will now run the following command for you:
 . "/Users/pierlu/Freqtrade-MGM/.env/bin/activate"; freqtrade test-pairlist --config "/Users/pierlu/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json" --quote USDT --print-json > /var/folders/4m/wxxp9ltd165bsly126kh8p640000gn/T/tmpcjvxqbah
INFO - freqtrade 2023.1.dev-772800bf7
INFO - Using config: /Users/pierlu/Freqtrade-MGM/user_data/mgm_tools/RetrieveTopVolumeStaticPairList.json ...
INFO - Verbosity set to 0
INFO - Using user-data directory: /Users/pierlu/Freqtrade-MGM/user_data ...
INFO - Using data directory: /Users/pierlu/Freqtrade-MGM/user_data/data/binance ...
INFO - Checking exchange...
INFO - Exchange "binance" is officially supported by the Freqtrade development team.
INFO - Using pairlist from configuration.
INFO - Validating configuration ...
INFO - Instance is running with dry_run enabled
INFO - Using CCXT 2.6.39
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Applying additional ccxt config: {'enableRateLimit': True}
INFO - Using Exchange "Binance"
INFO - Using resolved exchange 'Binance'...
INFO - Using resolved pairlist VolumePairList from '/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
INFO - Using resolved pairlist AgeFilter from '/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlist/AgeFilter.py'...
INFO - Using resolved pairlist PriceFilter from '/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
INFO - Using resolved pairlist ShuffleFilter from '/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py'...
INFO - Backtesting mode detected, applying seed value: None
ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/commands/pairlist_commands.py", line 29, in start_test_pairlist
    pairlists = PairListManager(exchange, config)
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlistmanager.py", line 35, in __init__
    pairlist_handler = PairListResolver.load_pairlist(
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/resolvers/pairlist_resolver.py", line 39, in load_pairlist
    return PairListResolver.load_object(pairlist_name, config,
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/resolvers/iresolver.py", line 182, in load_object
    found_object = cls._load_object(paths=abs_paths, object_name=object_name,
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/resolvers/iresolver.py", line 156, in _load_object
    return module(**kwargs)
  File "/Users/pierlu/Freqtrade-MGM/freqtrade/freqtrade/plugins/pairlist/ShuffleFilter.py", line 40, in __init__
    maxsize=1000, ttl=timeframe_to_seconds(self._config['timeframe']))
KeyError: 'timeframe'
CRITICAL - Unfortunately we could generate the static pairlist.
INFO - 🤖 Saving fresh static pairlist into mgm_pair_lists/Binance-USDT-Top-Volume-StaticPairList.json
INFO - 🍺 Saving pairlist as whitelist to "mgm-config.json"...

**Comment by truongnguyenptit** [comment]
same here

**Comment by sebastianmacias** [comment]
I'm having the same issue
